trying github actions to automate lighthouse tests

diff --git a/.github/workflows/lighthouse-ci.yml b/.github/workflows/lighthouse-ci.yml
--- a/.github/workflows/lighthouse-ci.yml
+++ b/.github/workflows/lighthouse-ci.yml
@@ -1,19 +1,25 @@
 name: Build project and run Lighthouse CI
+
 on: [push]
+
 jobs:
   lhci:
     name: Lighthouse CI
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v1
-      - name: Use Node.js 10.x
-        uses: actions/setup-node@v1
+      - uses: actions/checkout@v3
+
+      - name: Use Node.js 22.x
+        uses: actions/setup-node@v3
         with:
-          node-version: 10.x
-      - name: npm install
+          node-version: 22
+
+      - name: Install dependencies
         run: |
-          npm install
+          cd vite-project
+          npm ci
+
       - name: run Lighthouse CI
         run: |
-          npm install -g @lhci/cli@0.3.x
-          cd ./vite-project && lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
+          cd vite-project
+          npx lhci autorun || echo "LHCI failed!"
